# Template for development ado deployments
---
AWSTemplateFormatVersion: 2010-09-09
Description: Eucalyptus Cloud ADO development template

Parameters:

  DeploymentName:
    Description: Short deployment description (used in DNS)
    Type: String
    AllowedPattern: "[a-z0-9-]{1,32}"
    Default: devel

  AdoBuildId:
    Description: The build identifier for deployment / testing
    Type: String
    AllowedPattern: "[1-9][0-9]{2,6}"

  InstanceType:
    Description: Instance type
    Type: String
    AllowedValues:
      - c5d.2xlarge
      - c5d.4xlarge
      - c5d.metal
      - m5d.metal
    Default: c5d.2xlarge

  InstanceTypeSpotMaxPrice:
    Description: Maximum spot price for the instance type (2 for metal)
    Type: String
    Default: "0.4"

  KeyName:
    Description: Key Name
    Type: AWS::EC2::KeyPair::KeyName

  SshCidr:
    Description: CIDR for source of SSH connections
    Type: String
    Default: 0.0.0.0/0

  Zone:
    Description: Availability zone
    Type: AWS::EC2::AvailabilityZone::Name
    Default: us-west-1a

  DeployCephConverged:
    Description: Deploy with converged ceph storage
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "no"

  DevHostedZoneId:
    Description: Route53 hosted zone to use
    Type: String
    Default: Z03669683K9LKCWCNN3BJ

Conditions:

  UseKeyNameParameter: !Not
    - !Equals
      - !Ref KeyName
      - ""

Mappings:

  # From: https://wiki.centos.org/Cloud/AWS
  #
  # Development builds are hosted in us-west-1
  AWSRegion2AMI:
    us-west-1:
      CentOS7: ami-08d2d8b00f270d03b
    us-west-2:
      CentOS7: ami-0686851c4e7b1a8e1

Resources:

  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: 10.111.0.0/16
      Tags:
       - Key: stack-description
         Value: !Sub "ADO ansible dev build: ${AdoBuildId}"

  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      AvailabilityZone: !Ref Zone
      MapPublicIpOnLaunch: yes
      CidrBlock: 10.111.0.0/16
      Tags:
       - Key: stack-description
         Value: !Sub "ADO ansible dev build: ${AdoBuildId}"

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
       - Key: stack-description
         Value: !Sub "ADO ansible dev build: ${AdoBuildId}"

  InternetGatewayAttach:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Vpc
      InternetGatewayId: !Ref InternetGateway

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
      Tags:
       - Key: stack-description
         Value: !Sub "ADO ansible dev build: ${AdoBuildId}"

  RouteTableAssociate:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttach
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "ADO ansible dev build: ${AdoBuildId}"
      VpcId: !Ref Vpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SshCidr
        - IpProtocol: tcp
          FromPort: 53
          ToPort: 53
          CidrIp: !Ref SshCidr
        - IpProtocol: udp
          FromPort: 53
          ToPort: 53
          CidrIp: !Ref SshCidr
      Tags:
       - Key: stack-description
         Value: !Sub "ADO ansible dev build: ${AdoBuildId}"

  InstanceNetworkInterface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      GroupSet:
        - !GetAtt SecurityGroup.GroupId
      PrivateIpAddress: 10.111.0.10
      SubnetId: !Ref Subnet
      SourceDestCheck: no
      Tags:
        - Key: stack-description
          Value: !Sub "ADO ansible dev build: ${AdoBuildId}"

  InstanceEip:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  InstanceEipAssociate:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt InstanceEip.AllocationId
      NetworkInterfaceId: !Ref InstanceNetworkInterface

  RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref DevHostedZoneId
      RecordSets:
      - Name: !Sub "cloud-${DeploymentName}.qa.eucalyptuscloud.net."
        Type: NS
        TTL: 300
        ResourceRecords:
        - !Sub "ns1.cloud-${DeploymentName}.qa.eucalyptuscloud.net."
      - Name: !Sub "ns1.cloud-${DeploymentName}.qa.eucalyptuscloud.net."
        Type: A
        TTL: 300
        ResourceRecords:
        - !Ref InstanceEip

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !FindInMap
          - AWSRegion2AMI
          - !Ref AWS::Region
          - CentOS7
        BlockDeviceMappings:
          - DeviceName: /dev/sda1
            Ebs:
              VolumeSize: 20
        InstanceType: !Ref InstanceType
        KeyName: !If
          - UseKeyNameParameter
          - !Ref KeyName
          - !Ref AWS::NoValue
        NetworkInterfaces:
          - DeviceIndex: 0
            NetworkInterfaceId: !Ref InstanceNetworkInterface
        InstanceMarketOptions:
          MarketType: spot
          SpotOptions:
            MaxPrice: !Ref InstanceTypeSpotMaxPrice
            SpotInstanceType: one-time

  Instance:
    Type: AWS::EC2::Instance
    DependsOn: PublicRoute
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      UserData:
        Fn::Base64: !Sub |
          #cloud-config
          disable_root: no
          packages:
           - epel-release
           - git
           - lvm2
           - nvme-cli
          runcmd:
           - /root/dev.sh &
          write_files:
           - path: /etc/pki/rpm-gpg/RPM-GPG-KEY-eucalyptus-release-as
             permissions: 0644
             content: |
               The following public key can be used to verify RPM packages built
               and signed by AppScale Systems, Inc for Eucalyptus releases.
               
               -----BEGIN PGP PUBLIC KEY BLOCK-----
               
               mQENBFqy/18BCACzDLAmcAEalDnql2UBQySK+2BwXYPUPZXD/WknUHIYbIwFvUX1
               YedT5deJ5b8l/DJ2xclutfP9o7Q2MVFzaA92fhpliS6ZbkGRDPDv9Kmev+HYdkFS
               g7f62TzvQKiR5kxCnplnaeoA6Mn2JFWU7n950wYtdZZgpk5MOKHda5Ho6CRckKX6
               gMqXpJhk4wgb3AxbQRxyqisFCBnDBoTrJI8XR5gD8MIPGfLBY6XmbDO1MO5AWJle
               IaItAb08+Ggoi/gJMzE7O3nWYllABK6DK7Skazm9X6iRKv/MsNu3sqQNwiHhM+Cu
               BZH4PfCi6xYbgIG7K7Xe99VZQt2l0vX+e6vBABEBAAG0JUV1Y2FseXB0dXMgQnVp
               bGQgPGJ1aWxkQGFwcHNjYWxlLmNvbT6JAU4EEwEIADgWIQTX9i2L8FVEXRtZ78JQ
               KJzVxVFQQgUCWrL/XwIbAwULCQgHAgYVCgkICwIEFgIDAQIeAQIXgAAKCRBQKJzV
               xVFQQpSkB/9h0Acb4b9PkADZmXUOj8syplMJUhCuO5X8L3kCWI2JhLeES5Pbp2nW
               jm1EbkHWCDGtzbaN0uJIs1nJg6yDdlmkbbPjDO3UJk3UQ68grxn9nAl7jAMR/hDz
               hRHwyMEsnPz7OPzza5j+05sdWrsa7Gb4cLNMVqnfd+WHwwBmj1BgB2A5AFBtQDB0
               yzHsNDMHSBt14g7K07/fZ78PBFe4ALR0IdJG0eAVLpg/dKXEhNkduAKhXotHHR/M
               Nf/8LHxGwyuqNOf7qhnBwy1ISi9liiwmwCyilYVCzli9AbEXyFRUqp95PT4JXVt6
               PDKyNNcCtLv15bwC/DglDkbrQ46rdY1wuQENBFqy/18BCAC5t3GHdiKPkG9h79qM
               5XeSepXU+vMuK+FuzAkPkDrpb7uSIhdAOtYrPym2Tbxkat9Zx4PTAlzPmGoPIn+n
               8exAwVGJZTqQ7oo1TH0tLDh0qy4PRgYR3n7bcXgUtOqtCBzX7iY3KUZYVEsnf3Xd
               wQbzWryhV6RB9hZFotWyYwz8sv+a6D4WXx7ofdMUIdvOP61+b3fU3UuFZaee2xKj
               4Fp0lXvia1AQDUWqmhaL6jJz1qJ0SP247A+b/aD8SZEXwAyPdf92sjyAzo6ZRf+l
               p8vkcWWtw748r1k24RRlITlfg0o4os+7JureaVr76CKmpm/wn+k70kVkW/3+iJVE
               m3vfABEBAAGJATYEGAEIACAWIQTX9i2L8FVEXRtZ78JQKJzVxVFQQgUCWrL/XwIb
               DAAKCRBQKJzVxVFQQrihCACuNRtcyDWziGAb22qfnhj3JILLfZ7zEDLQMzZOxLG3
               40+ooEYfG98fhHntOD2vAGHoRvBzemloze356tX8UXUUfLzYjmv7i1kp0EGAAl+G
               kOzL7h+0cIdywAwy4BGTx13weEjDgQuGIKWzI5ynQthKHddR0PjHlUxhsLVpwIrd
               vvbdLHNsGTzDasHcrTMDyZP8NpHD6unFKBrfyDIB59QDHhZvmdA06OkTIJ+6X0BR
               CAbqr2Guq2D6YjnGULBq6xJRZkgThsC36ClktFhyQLAm0FuLxsYT8j4rs928wYtC
               hd5lKw4boxgjLF+UcYGchrV7U45wbrELY8ccwhmg4MVq
               =KpLt
               -----END PGP PUBLIC KEY BLOCK-----
           - path: /etc/pki/rpm-gpg/RPM-GPG-KEY-eucalyptus-release
             permissions: 0644
             content: |
               The following public key can be used to verify RPM packages built and
               signed by Eucalyptus Systems, Hewlett-Packard, and Hewlett Packard
               Enterprise for Eucalyptus products shipped after July of 2011, and for
               all updates to those products.
               
               Questions about this key should be sent to euca-security@hpe.com.
               
               pub  rsa4096/BE264D09C1240596 2011-07-29 Eucalyptus Systems, Inc. (release key) <security@eucalyptus.com>
               
               -----BEGIN PGP PUBLIC KEY BLOCK-----
               Version: GnuPG v1.4.15 (GNU/Linux)
               
               mQINBE4yDpIBEADNEtgH4rY7UvCJ5M/i3z1hNaIPyWaDx2CpiCDR+P13eDDBSQ7m
               9n8lOKYQtFG3v37XgtNeZSiKvcelNflYsAlGohcPnGcYE3QU58oq7nBhKer2ozdQ
               3GDm/KxsvwUF2sqiRHG+HVcK3QGeZHaOGhIj2n/4d0dmbphvDf7EzYhsz+ylZGRo
               0S1jL1VXi1hDqjTNYvdv3BS2lmpRKnfuyTF2vBP11m/i2y0JvrZkWgQB1CcMU1U5
               tQSuxV6q0e2rTU3w4NPrDJwC9+Y2ajWGGZozqyN+tPJ6DZTbql/5msFJXdS2tvKq
               nWvyo5M2Ke92tn6JnNWl6a/NudtQOitlgky0DkgFhTGArGwPImdhKGTOsQOw2vln
               SbhOOd0+Fg8woEM8S27ViVH75ULe5WsxqzN9EdlgFh0JfFT6HgN95U5o+yjOsAr3
               xaX/r1uyevooe3ow+MiFEMYlASgkxfjklveaPE4b00n/cZSq03i0Fz5+Nwgq1Uwj
               wqSEJMOGtBO2sXroB7Qzcm1dlQJL2au+by5yFvmIR3v2tDyu84T4SVSMfU61B0+b
               Z2+ufwUrGHkvQSEmfI3NswzJKP4lEh52VaLQx9NZ0qYlap2i3QkW+xCx37VTAViU
               TbggQzck25fiIveVpyi/0khDHio3ZeX06i4XoAdtsaYckfROzpwZnu0MawARAQAB
               tEBFdWNhbHlwdHVzIFN5c3RlbXMsIEluYy4gKHJlbGVhc2Uga2V5KSA8c2VjdXJp
               dHlAZXVjYWx5cHR1cy5jb20+iQI4BBMBAgAiBQJOMhAnAhsDBgsJCAcDAgYVCAIJ
               CgsEFgIDAQIeAQIXgAAKCRC+Jk0JwSQFluz9D/sHoShHF6MCc+c+VI8yYHXAkv7h
               nOahm/H76Pnt1VTGI2J4Sl+A/e3KpGjxa3Ii8xN5MhQNQ9jSJFDdLuaD4BmbjZF3
               WOObFvgTTw42mfXrUo/F4sthVwEvU4o1cvfVyM91kzg5X6u8K91gcVmsJvPOn3Uh
               Z7SQOfv0BzbBb6XR3Wi5fvMlE0Tfbc2SEJ1l0Au9QjvuH2tVfCaHkPsWn6s8ONfQ
               l+jclkfZNjfaAPStMj8ZylizA0Wgib+RffNAe8BlbGrZwum8Sk005jhGKkQmYz7L
               nMg8dPIvQFxKeQddE4o11Jy9LUMXuJBsu2TMFWf1zEzrVi+BzBj61HeM3CbTYO9i
               fbOhYdiaRtHHuWnH2Nh7+u2rDkU1lfNotFM1yEoldhYnHklN2ZB4OiY3yCG1a4qN
               KYTshqoyQPOa8PYAObydKJweNgNRhO74s6AZHMR4TR/Mp+cgXMXZIbnuxut0UwkC
               GditoANmgURXaZ2GA3Vy+5IgNCwJjOikjeGZLqijCj5T92Viju70UW8nipp5eIXp
               i23Z9QLc/+V1HhkiONLLAaGPCuAtvPLOCkALKjKOBJ4uMdPRl/Vqo2S7URUbjml1
               tZQspPYhQh95SwUg0imvo7k2UO4sW/Tatq3oS25T9wtJYREYjn4MbEUI0FBxGn5k
               2T2jSGSw43cM9hVBqQ==
               =Xs3z
               -----END PGP PUBLIC KEY BLOCK-----
               
           - path: /etc/yum.repos.d/eucalyptus-base.repo
             permissions: 0644
             content: |
               [eucalyptus-base]
               name=Eucalyptus 5 Base - $basearch
               baseurl=https://downloads.eucalyptus.cloud/software/eucalyptus/base/5/rhel/7/x86_64/
               gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-eucalyptus-release-as
                      file:///etc/pki/rpm-gpg/RPM-GPG-KEY-eucalyptus-release
               gpgcheck=1
               enabled=1
               fastestmirror_enabled=0
           - path: /etc/yum.repos.d/eucalyptus.repo
             permissions: 0644
             content: |
               [eucalyptus]
               name=Eucalyptus 5 - $basearch
               baseurl=https://downloads.eucalyptus.cloud/software/eucalyptus/dev/ado/${AdoBuildId}/
               gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-eucalyptus-release-as
                      file:///etc/pki/rpm-gpg/RPM-GPG-KEY-eucalyptus-release
               gpgcheck=1
               enabled=1
               fastestmirror_enabled=0
           - path: /root/setup.sh
             permissions: 0755
             content: |
               #!/bin/bash
               set -eux
               
               DISK_DEVICE=""
               if [ -e /dev/nvme4n1 ] ; then
                 DISK_DEVICE="/dev/disk_vg/disk_lv"
                 vgcreate disk_vg /dev/nvme3n1
                 vgcreate ceph_vg /dev/nvme4n1
                 lvcreate --extents "100%FREE" --name disk_lv disk_vg
                 lvcreate --extents "100%FREE" --name ceph_lv ceph_vg
               else
                 DISK_DEVICE="/dev/ceph_vg/disk_lv"
                 vgcreate ceph_vg /dev/nvme1n1
                 lvcreate --size "150G" --name disk_lv ceph_vg
                 lvcreate --extents "100%FREE" --name ceph_lv ceph_vg
               fi
               mkfs -t xfs -L disk-lv ${!DISK_DEVICE}
               mkdir -pv /disk
               mount ${!DISK_DEVICE} /disk
               
               ssh-keygen -q -t rsa -f "/root/.ssh/id_rsa" -N ""
               cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
           - path: /root/deploy.sh
             permissions: 0755
             content: |
               #!/bin/bash
               set -eux
               yum --assumeyes install eucalyptus-ansible
               ansible-playbook --inventory /root/inventory.yml /usr/share/eucalyptus-ansible/playbook_vpcmido.yml
           - path: /root/dev.sh
             permissions: 0755
             content: |
               #!/bin/bash
               { /root/setup.sh && /root/deploy.sh ; } &> /root/dev.log
           - path: /root/inventory.yml
             permissions: 0644
             content: |
               all:
               
                  hosts:
               
                    host10:
                      ansible_connection: local
                      host_cluster_ipv4: 10.111.0.10
                      host_public_ipv4: 10.111.0.10
                      host_zone_key: 1
               
                  vars:
               
                    eucalyptus_yum_baseurl: 'https://downloads.eucalyptus.cloud/software/eucalyptus/dev/ado/${AdoBuildId}/'
                    eucalyptus_base_yum_enabled: Y
               
                    eucalyptus_console_cloud_deploy: no
                    eucalyptus_console_certbot_enable: no
                    eucalyptus_services_certbot_enable: no
               
                    cloud_service_image_rpm: yes
                    cloud_firewalld_configure: no
                    cloud_firewalld_always_reload: no
                    cloud_firewalld_cluster_cidr: 10.111.0.0/16
                    cloud_firewalld_cluster_interface: "{{ eucalyptus_host_cluster_interface }}"
               
                    cloud_public_port: 8773
                    cloud_region_name: us-euca-1
                    cloud_system_dns_dnsdomain: cloud-${DeploymentName}.qa.eucalyptuscloud.net
               
                    cloud_opts_mem: "-Xmx4g"
                    cloud_instances_state_dir: /disk/eucalyptus/instances
               
                    ceph_release: nautilus
                    ceph_osd_data_path: ceph_vg/ceph_lv
                    ceph_public_network: 10.111.0.0/16
                    ceph_converged: ${DeployCephConverged}
               
                    vpcmido_public_ip_range: 10.111.100.100-10.111.100.200
                    vpcmido_public_ip_cidr: 10.111.100.0/24
               
                  children:
               
                    console:
                      hosts:
                        host10:
               
                    cloud:
                      hosts:
                        host10:
               
                    zone:
                      hosts:
                        host10:
               
                    node:
                      hosts:
                        host10:
      Tags:
       - Key: stack-description
         Value: !Sub "ADO ansible dev build: ${AdoBuildId}"
       - Key: Name
         Value: !Sub "eucalytpus-dev-${AdoBuildId}-ciab"

Outputs:

  InstanceId:
    Description: Instance
    Value: !Ref Instance

  Ip:
    Description: Instance IP
    Value: !GetAtt Instance.PublicIp

  Hostname:
    Description: Instance hostname
    Value: !GetAtt Instance.PublicDnsName

